// webview-ui/src/components/MermaidBlock.tsx
//
// V2.1.2 spec-fix-9: inline mermaid diagram rendering for the spec page.
//
// Why this exists:
//   The design.md generated by the planner agent includes mermaid-fenced
//   ER diagrams and sequence diagrams. ReactMarkdown without intervention
//   renders these as plain code blocks — readable but not visual. This
//   component intercepts ```mermaid blocks and renders them as inline SVG
//   the same way GitHub does.
//
// How it works:
//   1. mermaid.render() is async and returns SVG-as-string. We call it in
//      useEffect after mount and store the result in state.
//   2. The unique element ID required by mermaid comes from a module-level
//      counter — simpler than UUID, sufficient for the no-collision-within-
//      a-single-page guarantee mermaid actually needs.
//   3. Parse errors fall back to a styled code block + error banner.
//      Never propagates exceptions — the spec page must keep working
//      even if one diagram is malformed.
//   4. mermaid.initialize() runs once at module load with dark theme.
//      VS Code's webview is dark-by-default for our users; theme-reactive
//      switching is a v2 polish item.

import { useEffect, useRef, useState } from 'react';
import mermaid from 'mermaid';

// One-time mermaid configuration. Theme matches VS Code dark default;
// transparent background lets the spec panel's color show through.
//
// `securityLevel: 'strict'` blocks click handlers and arbitrary HTML
// inside diagram labels. We're rendering LLM-generated diagrams that
// the model could in principle ask to embed scripts; strict mode is
// the right default for a tool processing untrusted input.
//
// `startOnLoad: false` because we control rendering ourselves via
// the render() API. Auto-load would try to scan the DOM for .mermaid
// elements and fight our React lifecycle.
let mermaidInitialized = false;
function ensureMermaidInitialized() {
    if (mermaidInitialized) { return; }
    mermaidInitialized = true;
    mermaid.initialize({
        startOnLoad: false,
        theme: 'dark',
        securityLevel: 'strict',
        // Match VS Code's monospace font so diagram text feels native.
        fontFamily: 'var(--vscode-editor-font-family, "SF Mono", Menlo, Consolas, monospace)',
        themeVariables: {
            // Background transparent → inherits spec panel color.
            // Edge/text colors use VS Code variables so the diagram
            // adapts when the user switches themes (light, high-contrast).
            background: 'transparent',
            primaryColor: '#264f78',           // VS Code blue accent
            primaryTextColor: '#cccccc',
            primaryBorderColor: '#454545',
            lineColor: '#858585',
            secondaryColor: '#37373d',
            tertiaryColor: '#252526',
        },
    });
}

// Module-level counter for unique render IDs. mermaid.render() needs a
// unique DOM ID for each call; collisions cause one diagram to overwrite
// another. A simple monotonic counter is sufficient — we only need
// uniqueness within a single page render, not across sessions.
let renderCounter = 0;

interface MermaidBlockProps {
    /** The raw mermaid source (the contents of a ```mermaid block). */
    chart: string;
}

/**
 * Render a mermaid diagram inline. Async-rendered into SVG.
 *
 * Three visible states:
 *   1. Loading — small placeholder while the first render completes
 *      (typically ~50-200ms; user usually doesn't see it after warm-up).
 *   2. Rendered — the SVG diagram, sized to fit its container.
 *   3. Error — original source code + error message, in a styled
 *      block that doesn't break surrounding layout.
 */
export function MermaidBlock({ chart }: MermaidBlockProps) {
    const [svg, setSvg] = useState<string>('');
    const [error, setError] = useState<string | null>(null);
    const containerRef = useRef<HTMLDivElement>(null);

    useEffect(() => {
        // Mermaid needs to be initialized before the first render call.
        // Idempotent — only the first call actually does anything.
        ensureMermaidInitialized();

        // Reset error/svg on chart change so a previous error doesn't
        // persist if the user fixes the diagram source.
        setError(null);

        let cancelled = false;
        const id = `nexus-mermaid-${++renderCounter}`;

        // Async render. mermaid.render returns { svg, bindFunctions? }.
        // We discard bindFunctions because securityLevel: 'strict' disables
        // them — no click handlers needed for our use case.
        mermaid.render(id, chart)
            .then(({ svg }) => {
                if (cancelled) { return; }
                setSvg(svg);
            })
            .catch((err: unknown) => {
                if (cancelled) { return; }
                // Surface a useful message — mermaid errors usually point
                // at a specific line, so show what the parser reported.
                const msg = err instanceof Error ? err.message : String(err);
                setError(msg);
                setSvg('');
            });

        return () => {
            cancelled = true;
        };
    }, [chart]);

    if (error) {
        // Failed parse: show the raw mermaid source + the parser's error.
        // Use the same code-block styling other code chunks get so it
        // visually fits even though it's "wrong."
        return (
            <div className="nexus-mermaid-error">
                <div className="nexus-mermaid-error-banner">
                    ⚠ Mermaid diagram could not be rendered: {error}
                </div>
                <pre className="nexus-mermaid-error-source">{chart}</pre>
            </div>
        );
    }

    if (!svg) {
        // Loading state. Brief — usually <200ms. Shown as a skeleton-style
        // placeholder so the user knows something's happening rather than
        // staring at an empty space.
        return <div className="nexus-mermaid-loading">⋯ Rendering diagram...</div>;
    }

    // Render the SVG. dangerouslySetInnerHTML is necessary because mermaid
    // returns SVG as a string, not React elements. The SVG content comes
    // from mermaid's own renderer (we're not injecting user HTML), and
    // securityLevel: 'strict' above sanitizes anything the diagram source
    // might try to embed — combination provides defense in depth.
    return (
        <div
            ref={containerRef}
            className="nexus-mermaid-block"
            dangerouslySetInnerHTML={{ __html: svg }}
        />
    );
}